-- Tabla de Turnos
create table public.turnos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  telefono text,
  nombre text not null,
  dni text,
  motivo text,
  fecha date not null,
  hora text not null,
  primera_vez text, -- 'Si' o 'No'
  
  -- Restricciones opcionales
  constraint turnos_fecha_hora_key unique (fecha, hora)
);

-- Habilitar RLS (Seguridad a nivel de fila)
alter table public.turnos enable row level security;

-- Política: Permitir lectura pública (o restringir si se implementa auth real)
-- Por ahora, para el bot, permitimos acceso anonimo si se usa la key anonima
create policy "Acceso total con anon key"
on public.turnos
for all
to anon
using (true)
with check (true);
